### ISSUE TITLE
Data Pipeline won't run: Missing Schema invalid URL

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/Beiwe-Analysis#5]
Edit: Okay, I've seen that there are some changes in [custom_utils.py](https://github.com/onnela-lab/Beiwe-Analysis/blob/pipeline/Pipeline/custom_utils.py) that may fix the error that I'm pointing out in this thread.  If anyone in my same situation reads this, I'll be following the instructions from [Data Analysis Pipeline setup instructions](https://github.com/onnela-lab/beiwe-backend/wiki/Data-Analysis-Pipeline-setup-and-update-instructions) to update the container (follow all steps, but check step 3.ix in the section "Creating and deploying Docker containers to run the Data Pipeline code on the server")

I used the pipeline branch (from a while ago) to create the container in AWS Batch, but I had to copy the `download_s3_files.py` and uplad_s3_files.py files from `beiwe-backend` to the `Pipeline/utils` folder so it could run (last time that I tried to run it was some months ago). If I didn't add these files the container wasn't able to download the files.

However, these last days I've been trying to run the Data Pipeline on some studies, but I've seen in the AWS Batch that the jobs have failed. These are the messages from the AWS Batch container:

> Traceback (most recent call last):
> 
>  File "/home/beiwe-analysis/Pipeline/utils/download_s3_files.py", line 71, in <module>
> 
>  run(_local_file)
> 
>  File "/home/beiwe-analysis/Pipeline/utils/download_s3_files.py", line 56, in run
> 
>  resp = requests.post(data_access_api_url, data=payload)
> 
>  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 112, in post
> 
>  return request('post', url, data=data, json=json, **kwargs)
> 
>  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
> 
>  return session.request(method=method, url=url, **kwargs)
> 
>  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 494, in request
> 
>  prep = self.prepare_request(req)
> 
>  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 437, in prepare_request
> 
>  hooks=merge_hooks(request.hooks, self.hooks),
> 
>  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 305, in prepare
> 
>  self.prepare_url(url, params)
> 
>  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 379, in prepare_url
> 
>  raise MissingSchema(error)
> 
> requests.exceptions.MissingSchema: Invalid URL 'url.com/get-data/v1': No schema supplied. Perhaps you meant http://url.com/get-data/v1?
> 
> Traceback (most recent call last):
> 
>  File "/home/beiwe-analysis/Pipeline/manually.py", line 66, in <module>
> 
>  subprocess.check_call(['python3', join(UTILS, 'download_s3_files.py'), download_file])
> 
>  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
> 
>  raise CalledProcessError(retcode, cmd)
> 
> subprocess.CalledProcessError: Command '['python3', '/home/beiwe-analysis/Pipeline/utils/download_s3_files.py', '/home/raw-data-2019-12-23T12-43-21-953696/data.zip']' returned non-zero exit status 1

Is there any update that I missed? I've seen that there are 3 branches that are ahead of master:

- `pipeline`: the one that we are supposed to use, 46 commits ahead of master, Latest commit cf16519 on 23 Jul.
- `pipeline-updates`: it seems that this might be the "dev" branch, 46 commits ahead of master, Latest commit cf16519 on 23 Jul. It seems that these changes were already added to `pipeline`.
- `dashboard_update`:  43 commits ahead of master, Latest commit 2f86ee0 on 11 Jul. I couldn't see these changes in `pipeline`.

Do I have to just add the https to the url so that the `requests` library does not throw an exception?  Maybe I did wrong in adding the files from `beiwe-backend` to the `Pipeline/utils`... 

Thank you very much!

**Comment by usanchez** [comment]
Okay, following this issue, I tried to update the `Pipeline` container in `AWS`. However, I got some concerns and errors:

- Trying to run these commands...

```
sudo yum install -y gcc git
git clone https://github.com/onnela-lab/beiwe-backend.git --branch master
sudo pip install -r beiwe-backend/Requirements.txt
sudo pip install -r beiwe-backend/pipeline/requirements.txt
```
I got the following error:

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aPt2X9/psycopg2/

To solve it, I had to install some other packages:

```
sudo yum install gcc python-setuptools python-devel postgresql-devel
```
(I think that the one relevant here is `postgresql-devel`)

- I think that we are installing everything in the previous commands with `Python2`, when the code in `beiwe-backend` is suited for `Python3`, right? Shouldn't we run these commands with `pip3`?
- Is step `3.vii` relevant if what I want is to update the container? Shouldn't I jump straight to the step `3.viii`? There is nothing in this `3.vii`th step referring to updates.
- In the step `3.viii` I got the following error when running `python beiwe-backend/pipeline/update_docker.py`:
Traceback (most recent call last):

>   File "beiwe-backend/pipeline/update_docker.py", line 6, in <module>
>     import docker_script
>   File "/home/ec2-user/beiwe-backend/pipeline/docker_script.py", line 13, in <module>
>     from .script_helpers import set_default_region
> ValueError: Attempted relative import in non-package

Should we [use it as a package](https://stackoverflow.com/questions/11536764/how-to-fix-attempted-relative-import-in-non-package-even-with-init-py)? Or does this error raise because it should be run with `Python3` instead of `Python2`?

Thank you very much.

Best wishes and happy new year! :D

**Comment by biblicabeebli** [comment]
(Sorry, did not see I had a notification from the pipeline repo.)

Ah, this is because we updated to 2.8 of the psychopg2 library.  It no longer ships with a precompiled library for complex reasons, instead it makes you compile.

 I've updated the documentation with those requirements.

**Comment by biblicabeebli** [comment]
python 2 vs 3.

The pipeline deploy code is .... strange.  It is a script and a server endpoint that share common code.  However, because the server used to set up the docker container doesn't actually run the rest of the codebase it doesn't really matter.

The error your pipeline is emitting does not look to me like it stems from the setup hassles, I think it means your beiwe-backend servers do not have the url environment variable set  correctly.  The url is a critical detail because it is what the pipeline environments check to see where to upload the data.

**Comment by biblicabeebli** [comment]
*right, python version.
I do not even know if the aws linux server runs python3, I will need to investigate related setup for that, might need to do all the python 3 installs.

I'm of the opinion that this should be converted to a new launch script command.  (Pipeline setup was built while the cluster management code was still in-development, it kinda does its own thing.)

**Comment by biblicabeebli** [comment]
> Do I have to just add the https to the url so that the requests library does not throw an exception? Maybe I did wrong in adding the files from beiwe-backend to the Pipeline/utils...

I think you do, yes. (did not see this question on my first pass.)

**Comment by usanchez** [comment]
Hi Eli, thanks for your comments. My reply to them:

1. Thanks for updating the docs, tried the new commands on a fresh EC2 and the installation completes with no errors!
2. About the Py2 vs Py3 for the pipeline code: I think I understand now that Py3 is for pipeline code and Py2 for the docker setup code. The Amazon Linux 1 AMI runs `Python 2.7.16` btw.
3. About the error `ValueError: Attempted relative import in non-package`: I'm having this error in a fresh EC2. It raises the same error with both the setup and the update commands (`python beiwe-backend/pipeline/setup_batch.py` and `python beiwe-backend/pipeline/update_docker.py`:

>   File "beiwe-backend/pipeline/setup_batch.py", line 5, in <module>
>     import ami_script, docker_script, job_queue_script
>   File "/home/ec2-user/beiwe-backend/pipeline/ami_script.py", line 12, in <module>
>     from .script_helpers import set_default_region
> ValueError: Attempted relative import in non-package

and

> Traceback (most recent call last):
>   File "beiwe-backend/pipeline/update_docker.py", line 6, in <module>
>     import docker_script
>   File "/home/ec2-user/beiwe-backend/pipeline/docker_script.py", line 13, in <module>
>     from .script_helpers import set_default_region
> ValueError: Attempted relative import in non-package

It's strange because it fails at the imports, not when trying to run anything else... Regarding your comment about this, how can I check whether the beiwe-backend servers have the url environment variable set correctly?

I've been looking for this error online and got these answers:

- [Reddit thread](https://www.reddit.com/r/django/comments/44b5zl/attempted_relative_import_in_nonpackage/): They say that the error raises because _the folder is missing an `__init__.py` file to be considered a package_. The folder already contains this file (although I cannot totally understand what the content of this specific file does, compared to other `__init__.py` files that are empty), so this should not be the issue.
- [Github issue](https://github.com/oanda/oandapy/issues/42): Fixed by their [pull request](https://github.com/oanda/oandapy/pull/43), where they just changed their relative imports to absolute imports.
- [Kodi forum thread](https://forum.kodi.tv/showthread.php?tid=343005): One post states "Entry-point scripts are not considered a part of a package (their own location path prevails when resolving module/package names) so relative intra-package import syntax does not apply here." In our case, the entry points are `setup_batch.py` and `update_docker.py`, and, if what this guy says is true, they are not considered a package when they try to import `script_helpers.py`, and that's why the error raises, because relative imports cannot be used in non-packages.
- [Github issue](https://github.com/gabrielfalcao/lettuce/issues/203): They highlight that relative imports for intra-package imports are highly discouraged, and they say that the solution is to change the imports to absolute imports. Discovered in this thread, in [PEP8](https://www.python.org/dev/peps/pep-0008/), they say that:

> "Standard library code should avoid complex package layouts and always use absolute imports. However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose. Implicit relative imports should never be used and have been removed in Python 3."

So I'm gonna try to use absolute imports, that is, I'll append "pipeline" to all the imports that start with a ".". I'll update the results of this test.

Edit: Appending "pipeline" to the problematic imports to convert them to absolute imports didn't work:

> Traceback (most recent call last):
>   File "beiwe-backend/pipeline/update_docker.py", line 6, in <module>
>     import docker_script
>   File "/home/ec2-user/beiwe-backend/pipeline/docker_script.py", line 13, in <module>
>     from pipeline.script_helpers import set_default_region
> ImportError: No module named pipeline.script_helpers

Test2: I'll just remove the leading dot "." from these problematic imports, for science. I've seen in other files like `script_helpers.py` and `job_queue_script.py` that they don't use relative or absolute imports (they have the leading dot "." removed) so let's try that.
Edit2: It seems to be working lol
Edit3: Docker pushed! Instructions completed! I'll test now to run the Data Pipeline from the web.

**Comment by usanchez** [comment]
I'll keep this here, but I moved this issue to https://github.com/onnela-lab/beiwe-backend/issues/105 because is more related to the backend and not to the docker script or data pipeline execution.

-------------------------

When I try to run the Data Pipeline manually from a study, I get this issue:

> Exception: get_current_region can only be called on an amazon server with ec2metadata/ec2-metadata installed

I'll try to see why this happened and keep this post updated.

Edit: I went to the logs of ElasticBeanstalk and got this:

> ERROR in app: Exception on /run-manual-code/2 [POST]
> Traceback (most recent call last):
>    File "/opt/python/current/app/pipeline/configuration_getters.py", line 107, in get_current_region
>      return full_region.split(" ")[1][:-1]
> TypeError: a bytes-like object is required, not 'str'
>  
> During handling of the above exception, another exception occurred:
>  
>  Traceback (most recent call last):
>    File "/opt/python/current/app/pipeline/configuration_getters.py", line 111, in get_current_region
>      return check_output(["ec2metadata", "--availability-zone"]).strip()[:-1]
>    File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
>      **kwargs).stdout
>    File "/usr/lib64/python3.6/subprocess.py", line 423, in run
>      with Popen(*popenargs, **kwargs) as process:
>    File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
>      restore_signals, start_new_session)
>    File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
>      raise child_exception_type(errno_num, err_msg, err_filename)
>  FileNotFoundError: [Errno 2] No such file or directory: 'ec2metadata': 'ec2metadata'
>  
> During handling of the above exception, another exception occurred:
>  
> Traceback (most recent call last):
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
>      response = self.full_dispatch_request()
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
>      rv = self.handle_user_exception(e)
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
>      reraise(exc_type, exc_value, tb)
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
>      raise value
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
>      rv = self.dispatch_request()
>    File "/opt/python/run/venv/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
>      return self.view_functions[rule.endpoint](**req.view_args)
>    File "/opt/python/current/app/libs/admin_authentication.py", line 174, in authenticate_and_call
>      return some_function(*args, **kwargs)
>    File "/opt/python/current/app/api/data_pipeline_api.py", line 20, in run_manual_code
>      pipeline_region = get_current_region()
>    File "/opt/python/current/app/pipeline/configuration_getters.py", line 113, in get_current_region
>      raise Exception("get_current_region can only be called on an amazon server with ec2metadata/ec2-metadata installed")
> Exception: get_current_region can only be called on an amazon server with ec2metadata/ec2-metadata installed
>  
> Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
> ['Exception: get_current_region can only be called on an amazon server with ec2metadata/ec2-metadata installed', '  File "flask/app.py", line 2446, in wsgi_app', '  File "flask/app.py", line 1951, in full_dispatch_request', '  File "flask/app.py", line 1820, in handle_user_exception', '  File "flask/_compat.py", line 39, in reraise', '  File "flask/app.py", line 1949, in full_dispatch_request', '  File "flask/app.py", line 1935, in dispatch_request', '  File "libs/admin_authentication.py", line 174, in authenticate_and_call', '  File "api/data_pipeline_api.py", line 20, in run_manual_code', '  File "pipeline/configuration_getters.py", line 113, in get_current_region']

As a summary:

1. Code related error:
    - File: "/opt/python/current/app/pipeline/configuration_getters.py",
    - Line: 107
    - Method: in get_current_region
    - Statement: `return full_region.split(" ")[1][:-1]`
    - Error: `TypeError: a bytes-like object is required, not 'str'`
2. Missing `ec2metadata`: `get_current_region` can only be called on an amazon server with `ec2metadata/ec2-metadata` installed.

For this error, could we make so instead of requiring the EC2 to have `ec2metadata` installed, we could just get the information form a `curl` to `http://169.254.169.254`?

If we run `curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document` we will get the detail of the EC2 running the command. For example, in my case, I can get this info from running that command on the environment machine:

> {
>   "accountId" : <hidden by me>,
>   "architecture" : "x86_64",
>   "availabilityZone" : "eu-west-1b",
>   "billingProducts" : null,
>   "devpayProductCodes" : null,
>   "marketplaceProductCodes" : null,
>   "imageId" : <hidden by me>,
>   "instanceId" : <hidden by me>,
>   "instanceType" : "t2.medium",
>   "kernelId" : null,
>   "pendingTime" : <hidden by me>,
>   "privateIp" : <hidden by me>,
>   "ramdiskId" : null,
>   "region" : "eu-west-1",
>   "version" : <hidden by me>
> }

As you see, we could process this JSON and get the `region id` without imposing the requirement to install the `ec2metadata` package. What do you think?

3. I should set up my Sentry server...

**Comment by usanchez** [comment]
I'll keep this here, but I moved this issue to https://github.com/onnela-lab/beiwe-backend/issues/105 because is more related to the backend and not to the docker script or data pipeline execution.

-----------------------------------

Okay, so I plugged in my suggested change for error 2 and got rid of error 1 too. This is the piece of code that I've plugged in `get_current_region`:

```python3
def get_current_region():
    ec2_instance_identity_url = "http://169.254.169.254/latest/dynamic/instance-identity/document"
    ec2_instance_identity_response = requests.get(ec2_instance_identity_url)
    ec2_instance_region = ec2_instance_identity_response.json()["region"]

    return ec2_instance_region
```

No checks or anything, it was a fast testing.

However, solving this, led me to the following new error:

>["FieldError: Invalid field name(s) for model StudyRelation: 'is_batch_user'.", '  File "api/data_pipeline_api.py", line 30, in run_manual_code', '  File "pipeline/index.py", line 37, in refresh_data_access_credentials', '  File "django/db/models/manager.py", line 85, in manager_method', '  File "django/db/models/query.py", line 459, in get_or_create', '  File "django/db/models/query.py", line 537, in _extract_model_params']
>OCCURRED 1 TIMES:
>FieldError("Invalid field name(s) for model StudyRelation: 'is_batch_user'.",)
>  File "/opt/python/current/app/api/data_pipeline_api.py", line 30, in run_manual_code
>    refresh_data_access_credentials('manually', ssm_client=ssm_client, webserver=True)
>  File "/opt/python/current/app/pipeline/index.py", line 37, in refresh_data_access_credentials
>    is_batch_user=True,
>  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
>    return getattr(self.get_queryset(), name)(*args, **kwargs)
>  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/query.py", line 459, in get_or_create
>    lookup, params = self._extract_model_params(defaults, **kwargs)
>  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/query.py", line 537, in _extract_model_params
>    "', '".join(sorted(invalid_params)),

The error is quite clear that the field `is_batch_user` is invalid for the model `StudyRelation`. If I go to `user_model.py`, I see that, indeed, that field does not exist in `StudyRelation`:

```python3
class StudyRelation(AbstractModel):
    """
    This is the through-model for defining the relationship between a researcher and a study.
    There are these relatioships:
        site admin
        study admin
        researcher
    """
    study = models.ForeignKey(
        'Study', on_delete=models.PROTECT, related_name='study_relations', null=False, db_index=True
    )
    researcher = models.ForeignKey(
        'Researcher', on_delete=models.PROTECT, related_name='study_relations', null=False, db_index=True
    )
    relationship = models.CharField(max_length=32, null=False, blank=False, db_index=True)

    class Meta:
        unique_together = ["study", "researcher"]

    def __str__(self):
        return "%s is a %s in %s" % (self.researcher.username,
                                     self.relationship.replace("_", " ").title(),
                                     self.study.name)
```

However, the field `is_batch_user` is referenced many times in the code and is located in `Researcher`:

```python3
class Researcher(AbstractPasswordUser):
    """
    The Researcher database object contains the password hashes and unique usernames of any
    researchers, as well as their data access credentials. A Researcher can be attached to
    multiple Studies, and a Researcher may also be an admin who has extra permissions.
    A Researcher uses web, so their passwords are hashed accordingly.
    """

    username = models.CharField(max_length=32, unique=True, help_text='User-chosen username, stored in plain text')
    site_admin = models.BooleanField(default=False, help_text='Whether the researcher is also an admin')

    access_key_id = models.CharField(max_length=64, validators=[standard_base_64_validator], unique=True, null=True, blank=True)
    access_key_secret = models.CharField(max_length=44, validators=[url_safe_base_64_validator], blank=True)
    access_key_secret_salt = models.CharField(max_length=24, validators=[url_safe_base_64_validator], blank=True)

    is_batch_user = models.BooleanField(default=False)
```

So, I think that we should remove the `is_batch_user` from the following piece of code that is located in the function `refresh_data_access_credentials` from `pipeline/index.py`, because that field does not exist in `StudyRelation`: 

```python3
StudyRelation.objects.get_or_create(
            study=study,
            researcher=mock_researcher,
            relationship=ResearcherRole.researcher,
            is_batch_user=True, # <-- This
        )
```

Additionally, in `admin_api.py`, function `add_researcher_to_study`, we also use the `StudyRelation.objects.get_or_create` function, but we don't filter by `is_batch_user`.

Also I found out that the parameters passed to the method are different:

- function `refresh_data_access_credentials` from `pipeline/index.py`, parameters: `study`, `researcher` and `relationship`.
- function `add_researcher_to_study` from `api/admin_api.py`, parameters: `study_id`, `researcher_id`, `relationship`

I guess that this does not matter because in one instance we are filtering by researcher object and in the second one we filter by researcher id. 

I see that the intention is to get (or create) those study relationships that contain Batch users, but as this problematic field is not in `StudyRelation`, maybe we could add this filter to the mock_researcher some lines above? What I mean is, instead of having this:

```python3
    researcher_name = 'BATCH USER {}'.format(freq)
    mock_researchers = Researcher.objects.filter(username=researcher_name)
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_without_password(researcher_name)
    else:
        mock_researcher = mock_researchers.get()
        mock_researcher.save()

    # Ensure that the Researcher is attached to all Studies. This allows them to access all
    # data via the DAA.
    for study in Study.objects.all():
        StudyRelation.objects.get_or_create(
            study=study,
            researcher=mock_researcher,
            relationship=ResearcherRole.researcher,
            is_batch_user=True,
        )
```

We could have this:

```python3
    researcher_name = 'BATCH USER {}'.format(freq)
    mock_researchers = Researcher.objects.filter(username=researcher_name, is_batch_user=True)
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_without_password(researcher_name)
    else:
        mock_researcher = mock_researchers.get()
        mock_researcher.save()

    # Ensure that the Researcher is attached to all Studies. This allows them to access all
    # data via the DAA.
    for study in Study.objects.all():
        StudyRelation.objects.get_or_create(
            study=study,
            researcher=mock_researcher,
            relationship=ResearcherRole.researcher
        )
```

And this would solve the issue (I think). What do you think? 

Maybe I've made a mistake elsewhere and this wall of text has no sense xD

**Edit**: I tested my proposed piece of code and got that the researcher/user _BATCH USER manually_ is not a batch user:

First, I tried to see whether I could get the `mock_researchers`:

```python3
In [1]: freq = "manually"     
In [2]: researcher_name = 'BATCH USER {}'.format(freq)         
In [3]: mock_researchers = Researcher.objects.filter(username=researcher_name)                                              
In [4]: mock_researchers.get().username                                                                                     
Out[4]: 'BATCH USER manually'
```

There it is, now, trying the new way of filtering:

```python3
In [5]: mock_researchers = Researcher.objects.filter(username=researcher_name, is_batch_user=True)                         
In [6]: mock_researchers.get().username                                                                                    
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)
<ipython-input-11-60a2104c7648> in <module>
----> 1 mock_researchers.get().username

~/PycharmProjects/humanai-backend/venv/lib/python3.6/site-packages/django/db/models/query.py in get(self, *args, **kwargs)
    378             raise self.model.DoesNotExist(
    379                 "%s matching query does not exist." %
--> 380                 self.model._meta.object_name
    381             )
    382         raise self.model.MultipleObjectsReturned(

DoesNotExist: Researcher matching query does not exist.

In [7]: mock_researchers.get()                                                                                             
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)
<ipython-input-12-735bc98a09c6> in <module>
----> 1 mock_researchers.get()

~/PycharmProjects/humanai-backend/venv/lib/python3.6/site-packages/django/db/models/query.py in get(self, *args, **kwargs)
    378             raise self.model.DoesNotExist(
    379                 "%s matching query does not exist." %
--> 380                 self.model._meta.object_name
    381             )
    382         raise self.model.MultipleObjectsReturned(

DoesNotExist: Researcher matching query does not exist.
```

But it does not exist... So I tried to get the `is_batch_user` of this researcher:

```python3
In [8]: mock_researchers = Researcher.objects.filter(username=researcher_name)                                             
In [9]: mock_researchers.get().is_batch_user                                                                               
Out[9]: False
```

:surprised_pikachu_face:

I'll keep this post updated with the journey of discovering why this happened with the `is_batch_user` field...

**Edit2**: Okay, I think I got a reasonable explanation:

If the mock_researcher does not exist we create it with:
```python3
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_without_password(researcher_name)
```

If we go to the class method of Researcher:

```python3
    @classmethod
    def create_without_password(cls, username):
        """
        Create a new Researcher with provided username and no password
        """

        r = cls(username=username,
                password='fakepassword',
                salt='cab',
                admin=False) # --> I think that this may be obsolete, because the Researcher model does not have this field, shouldn't it be site_admin?
        r.reset_access_credentials()
        return r
```

Besides, the `admin` field being obsolete (IMO), here, there is no way to tell the class to create a `Researcher` with `is_batch_user` set to `True` and by default, when a `Researcher` is created this field is set to false (`is_batch_user = models.BooleanField(default=False)`). Additionally, the _only_ use for the `create_without_password` classmethod is to create the `mock_researchers`.

So my suggestion is to change these previously mentioned lines:

```python3
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_without_password(researcher_name)
```

to:

```python3
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_batch_user(username=researcher_name)
```

and additionally, changing the `create_without_password` classmethod to:

```python3
    @classmethod
    def create_batch_user(cls, username):
        """
        Create a new Researcher that serves as a Batch user
        """

        r = cls(username=username,
                password='fakepassword',
                salt='cab',
                site_admin=False,
                is_batch_user=True)
        r.reset_access_credentials()
        return r
```

Or, if you want to maintain the previous version of the method:

```python3
    if not mock_researchers.exists():
        mock_researcher = Researcher.create_without_password(username=researcher_name, is_batch_user=True)
```

and:

```python3
    @classmethod
    def create_without_password(cls, username, is_batch_user=False):
        """
        Create a new Researcher with provided username and no password
        """

        r = cls(username=username,
                password='fakepassword',
                salt='cab',
                site_admin=False,
                is_batch_user=is_batch_user)
        r.reset_access_credentials()
        return r
```

I'm so so sorry for this wall of text. Hope it helps anyway at least.

**Comment by biblicabeebli** [comment]
There was just a pull request that should have updated this code (it is on development, it is nearly ready for merging into master/production, I need to finish documentation).  I will try and re-review this bug.  When I get to that.

**Comment by usanchez** [comment]
I think that this issue can be closed, as it is also in beiwe-backend, and is already being discussed there.
