### ISSUE TITLE
Cannot find file "custom_pipeline.py"

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/Beiwe-Analysis#7]
I'm reviewing the setup of the beiwe-analysis repo, and while I was reading the comments in `manually.py`, I found out that I cannot find the file mentioned here:

> Beiwe-Analysis repo needs to exist in the user's home directory. This file is located at
>     /home/Beiwe-Analysis/Pipeline/custom_pipeline.py

It seems that is not relevant to the execution of the code, but that file is missing, it cannot be found in the repo. What did this file contain? Can it be relevant for the execution of the code?

**Comment by biblicabeebli** [comment]
It is ancient, I think it was the ingress spot for "stick custom stuff here".  this is superceeded by the new pipeline architecture which will actually support custom runtimes.
